/**
 * Renders a `.env`-compatible template of the variables the SDK
 * reads from the environment. Deliberately written by hand rather
 * than string-templated — easier to keep the shape stable across
 * SDK releases and easier for a merchant to copy/paste into their
 * own tooling.
 *
 * What this file DOES NOT contain: the PEM. The PEM is referenced
 * by a filesystem path (LINOPAY_PRIVATE_KEY_PEM_PATH) and lives
 * alongside `.env`, never inside it. If a merchant's automation
 * commits `.env` despite the warning, no key material leaks.
 */
export function renderEnvTemplate(opts: {
  keyId: string;
  baseUrl: string;
  environment: 'sandbox' | 'live';
  bankCode?: string;
  pemPath: string;
}): string {
  const lines: string[] = [
    '# LinoPay CLI / SDK configuration',
    '#',
    '# Generated by `linopay init`. The PEM itself is referenced by',
    '# the path below -- never paste its contents into this file.',
    '',
    `# Channel Key ID (kid) -- from your merchant portal's keys tab`,
    `LINOPAY_KEY_ID=${opts.keyId}`,
    '',
    '# LinoPay API base URL',
    '#   sandbox: https://sandbox.api.linopay.io',
    '#   live:    https://api.linopay.io',
    `LINOPAY_BASE_URL=${opts.baseUrl}`,
    '',
    `# Environment -- "sandbox" or "live". The SDK never infers this.`,
    `LINOPAY_ENVIRONMENT=${opts.environment}`,
    '',
    `# Default bank code (e.g. ANZ / ASB / BNZ / KIWIBANK / WESTPAC)`,
    ...(opts.bankCode ? [`LINOPAY_BANK_CODE=${opts.bankCode}`] : ['# LINOPAY_BANK_CODE=']),
    '',
    '# Filesystem path to the channel private key (PEM, PKCS#8)',
    `# -> Make sure "${opts.pemPath}" is in your .gitignore.`,
    `LINOPAY_PRIVATE_KEY_PEM_PATH=${opts.pemPath}`,
    '',
  ];
  return lines.join('\n');
}

/**
 * Builds a default `.env` path under the user's home directory when
 * no `--output` flag is supplied. Path chosen so a default init never
 * lands inside the project root a developer is working in (which is
 * where they'd be most likely to accidentally `git add .`).
 */
export function defaultPemPath(home: string): string {
  return `${home.replace(/[/\\]+$/, '')}/.linopay/key.pem`;
}
